# Generated by Django 4.2 on 2023-05-10 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=233)),
                ('logo', models.ImageField(upload_to='jobs/companies/logos')),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=233)),
                ('logo', models.ImageField(upload_to='scholarships/school/logos')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=233)),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='scholarship')),
                ('body', models.TextField(null=True)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('apply_button', models.URLField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.school')),
                ('tag', models.ManyToManyField(to='job.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('details', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('color', models.CharField(blank=True, choices=[('bg-[#3e06e5]', 'blue'), ('#ff758c', 'pink'), ('#764ba2', 'puple'), ('#ff7eb3', 'pink2'), ('#66a6ff', 'lightblue'), ('#fad0c4', 'orangy'), ('#fcb69f', 'lightorangy'), ('#ff9a9e', 'orangy2'), ('#f80759', 'redy'), ('#38ef7d', 'greeny'), ('#f7b733', 'yellowy')], default='#66a6ff', max_length=200, null=True)),
                ('salary', models.CharField(max_length=250, null=True)),
                ('apply_button', models.URLField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=500)),
                ('job_type', models.CharField(blank=True, choices=[('Remote', 'Remote'), ('InOffice', 'In-Office')], max_length=200, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.company')),
                ('tag', models.ManyToManyField(to='job.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('img', models.ImageField(null=True, upload_to='blog')),
                ('details', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('tag', models.ManyToManyField(to='job.tag')),
            ],
        ),
    ]
